import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

public class Test
{
    public static String encryptThisString(String input)
    {
        try{
            MessageDigest md = MessageDigest.getInstance("SHA-1");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger no= new BigInteger(1,messageDigest);
            String hashtext= no.toString(16);
            while(hashtext.length()<32)
            {
                hashtext="0"+hashtext;
            }
            return hashtext;
        }
        catch(NoSuchAlgorithmException e){
            throw new RuntimeException(e);
        }
    }
    public static void main(String args[] ) throws NoSuchAlgorithmException
    {
        System.out.println("HashCode generated by SHA-1 for:");
        Scanner sc=new Scanner(System.in);
        String s1=sc.nextLine();
        System.out.print(":" +encryptThisString(s1)+"\n");
        String s2=sc.nextLine();
        System.out.print(":" +encryptThisString(s2)+"\n");
    }
}
